### ISSUE TITLE
mismatch Hiro Ordinals indexer and ordinals.com

### ISSUE THREAD

**Issue by Sayplaydiv** [hirosystems/ordinals-api#100]
And there have been many similar cases recently.For example：
https://api.hiro.so/ordinals/v1/inscriptions/b0de8b9b59ddcee2227cd335be944f693509d67c9113092d8824889db4c7d491i0
https://ordinals.com/inscription/b0de8b9b59ddcee2227cd335be944f693509d67c9113092d8824889db4c7d491i0

**Comment by smcclellan** [comment]
@Sayplaydiv This is in progress and will be updated shortly.

**Comment by rafaelcr** [comment]
This appears to be an issue on the `ord` side: https://github.com/ordinals/ord/issues/2202

**Comment by smcclellan** [comment]
@Sayplaydiv This issue appears resolved. Please reopen if this is still an issue.
