### ISSUE TITLE
Recent inscription address changes not registered by indexer?

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-api#101]
Two inscriptions have been sold on a marketplace yet displayed with incorrect owner address (as if not transferred). 

**A. Displayed with wrong owner address:**
#7924731
https://ordinals.hiro.so/inscription/ae7f86223ba83611a9ed17fc1893a7180f5571abac8339337e416a5082ff9d0ai0
Displayed as owned by inscriber.
Actual owner: bc1p44dzs49w4h82gyj0q34x9mec98gp0w5e6pvdfpnku0kqx92ckclsmfj4hf
https://mempool.space/tx/7e13acac1e10fb8a6d92da2e5f6092e014eea49fa1afa825f0eb172b596e2013
(second output contains inscription)
May 22nd

#7924744
https://ordinals.hiro.so/inscription/dc288f9562b186379ca7bfe0c0d7668a2bad2e165876ab1e5f99fda7ede4d063i0
Displayed as owned by inscriber.
Actual owner: bc1pxlys68v8d8v7dh2p8psej8a5hlumw7lhgg4y9n7vnp695f2x78xsp960m6
Transfer transaction: https://mempool.space/tx/53d78aa777b9838b826417d598a5bac9dee536b12f5aca4ae3a01b14b6b1e2d0
(second output)
May 22nd

**B. Correct owner**
More recent similar sale from the same address is correctly shown. 
7924730
https://ordinals.hiro.so/inscription/bacafb0d51a06c4214dd1689a759fe929ca881410d9eccef9bf639faa7664506i0
Transfer transaction: https://mempool.space/tx/1a72210317b71c7ab2c4747fffa97013fa9a0efd9f0d17695326cbe5f27deda1
June 14th

**Comment by 314159265359879** [comment]
Quote/update from Ludo on discord:
**ludo — Today at 4:15 PM
Thanks Ken! I've been working on making transfer tracking more reliable, we're in the process of rebuilding an index from scratch. will update here once it's ready.**

**ludo — Today at 4:30 PM
yeah I understand how critical this bug is, related issues are tagged as urgent during triage and are my priority. the new index should be ready by end of week, then I'll need a bit of time to do some sanity checks.**

**Comment by smcclellan** [comment]
We are currently ingesting -- we intend to update this by tomorrow.

**Comment by 314159265359879** [comment]
@smcclellan 

Did the ingestion work out as expected? I have one more similar case today a user with several ordinal inscriptions that lack the update of the latest transfers in the Hiro ordinals explorer but they do show on ordiscan.com for example. 

Going out off the users wallet. 
I see 11481305
f75c8d90637bec3734bd61144ec21bdada274fcb61a045e04dadd15c622b27aci0
The latest transfer is not properly reflected by the Hiro ordinals explorer https://ordinals.hiro.so/inscription/f75c8d90637bec3734bd61144ec21bdada274fcb61a045e04dadd15c622b27aci0 that why it is still shown on bc1ps0sdn25mrv8qnj9fpegsqcjn3fk56tseh4wype7jt8vxl088metqf98y86 rather than on bc1pmtjjtmj8wmsf3qtqzz0ypmvulvqlq6wkxnt2ggkxku0yfwml6ldqju64tx 

11480986 
https://ordinals.hiro.so/inscription/9c62f6ae0093d30379ee9cd396c03dde4d2109a6ddd516cfd5245a4e4f68b30ai0 here to the latest transfer is not registered by the Hiro indexer: https://mempool.space/tx/c082d2e513c969c55242cde6da850092db9ef31755ceeda4be9d05d243497257

A similar situation for the recent ordinals coming into the wallet. 
12443406
https://ordinals.hiro.so/inscription/f62f8ca49b3e18f072f76612ad072740b808930889c0b18c230962a4d5dc6d3ai0
https://ordiscan.com/inscription/12443406

12446944
https://ordinals.hiro.so/inscription/b030626e15f3374877721142cb96f8bb00c1f44ff0aabf8eda15e9c5804d268ci0
https://ordiscan.com/inscription/12446944
https://bestinslot.xyz/ordinals/inscription/12446944
https://www.ord.io/12446944 (here the last three transfers have not been updated).

**Comment by rafaelcr** [comment]
Hi @314159265359879 the API ingestion is still working on a parallel environment, once it's done we'll switch traffic and we can validate these cases to make sure they're resolved

**Comment by jmbinette** [comment]
Same issue here, as the indexer been investigated?

**Comment by 314159265359879** [comment]
One more case (added here so we can easily retest after the traffic is switched to the environment with the fix. 

https://ordinals.hiro.so/inscription/9cf2f97f37ac130584f8c6ac6479f4b118cda42121aee389b404f4a5eaeb0402i0
Latest transactions (after June 10th mint) are not yet reflected on Hiro's ordinals explorer

https://bestinslot.xyz/ordinals/inscription/11287186
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/8df3e6ad-1f27-4ccc-a2f0-e0eab07e54c7)

**Comment by jmbinette** [comment]
> One more case (added here so we can easily retest after the traffic is switched to the environment with the fix.
> 
> https://ordinals.hiro.so/inscription/9cf2f97f37ac130584f8c6ac6479f4b118cda42121aee389b404f4a5eaeb0402i0 Latest transactions (after June 10th mint) are not yet reflected on Hiro's ordinals explorer
> 
> https://bestinslot.xyz/ordinals/inscription/11287186 ![image](https://user-images.githubusercontent.com/33360391/249871274-8df3e6ad-1f27-4ccc-a2f0-e0eab07e54c7.png)

Thanks 

Do we have an ETA ? 
Is it true to say that until the fix I cannot move the inscription ?

**Comment by 314159265359879** [comment]
@rafaelcr do you have an update/ETA for this fix?

**Comment by 314159265359879** [comment]
Another case where the most recent transfer is not reflected in the odinals.hiro.so explorer/api:
[e1bf4eeca3a4c083a55f1cea8bd5ee62676857f7768a4b674a5043b4efed5a6bi0](https://ordinals.hiro.so/inscription/e1bf4eeca3a4c083a55f1cea8bd5ee62676857f7768a4b674a5043b4efed5a6bi0)
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/9ede4ac7-0550-47f8-834a-62a75002890c)

https://ordiscan.com/inscription/14337715
This transfer has not been picked up: 
[![image](https://github.com/hirosystems/ordinals-api/assets/33360391/0b3966ed-68bf-4363-84b2-e6c4d22d391f)](https://mempool.space/tx/2911627e0e679a4bf32bb1b209fa255e5fd392a7637341a62e04c1528e94333f)

**Comment by 314159265359879** [comment]
Here is an address with two changes one is fine, the other is not yet reflected by the Hiro Ordinals Explorer for this address bc1pzu63x0uc9eghxj0pqf09mrr86xvy37j7ec7m2j08r3t4fnzmt8vs6vmks9

**1. The older one from June 20-23 is not up to date:** 
https://ordiscan.com/inscription/12443276
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/b2ddf600-0774-411f-baea-7f766295fff3)

In ordinals.hiro.so:
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/eb9553e4-dc38-4a9e-b126-ff5eb151fe16)

**2. The more recent change (July) does get picked up.** 
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/c871ce22-a70a-4dc5-8437-0663826c1f29)

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/e29bb634-6bab-47d1-80ca-077e12501964)

**Comment by rafaelcr** [comment]
Hi @314159265359879 sorry this has taken a while, we're very close to having the new index ready which will fix these issues, hopefully tomorrow we'll be able to switch to the new env. We appreciate your patience on this 🙏

**Comment by rafaelcr** [comment]
@314159265359879 apologies for the massive delays on this, but we've just deployed the latest index to our API which solves all of these issues! I validated some of the cases and they all seem corrected, but let me know if you still find some problems on this.
