### ISSUE TITLE
Difference in inscription number on Hiro compared to other indexers

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-api#102]
Originally reported by Leonidas (thanks!)
![image](https://github.com/hirosystems/ordinals-explorer/assets/33360391/05817054-12d0-40e6-8f1b-da3e0f2994ce)

Inscription #12517402
https://ordinals.hiro.so/inscription/441a57570b84336a1520076eb52aed6eb9dcab7bdcc98ac6fcfa7f65f8a4b3f1i0

![image](https://github.com/hirosystems/ordinals-explorer/assets/33360391/076116f1-9995-4412-8223-bf2ae515802a)

Inscription 12518005
https://ordinals.com/inscription/441a57570b84336a1520076eb52aed6eb9dcab7bdcc98ac6fcfa7f65f8a4b3f1i0 

![image](https://github.com/hirosystems/ordinals-explorer/assets/33360391/bca8b521-2267-4406-bd93-ffe33b9349ae)

This has been going on for about 2 hours. What happened ~two hours ago that may have caused this?

**Comment by smcclellan** [comment]
@314159265359879 This one is fixed. 👍

**Comment by 314159265359879** [comment]
I appreciate the ping, thanks for fixing it quickly!
