### ISSUE TITLE
trigger Vercel docs build when a new release is deployed

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/ordinals-api#103]
so docs can be updated without the need for a manual Vercel build

**Comment by LakshmiLavanyaKasturi** [comment]
This is dependent on the decision made for remote docs - https://github.com/hirosystems/docs/issues/356. @rafaelcr @CharlieC3

**Comment by CharlieC3** [comment]
@LakshmiLavanyaKasturi Is this still needed? Can it be closed?

**Comment by LakshmiLavanyaKasturi** [comment]
I see an issue with the build cache. It looks like, Netlify is picking the old cache, and the deployment still fails after refreshing the build using the "redeploy" button from Vercel.

Eg, In the PR: https://github.com/hirosystems/docs/pull/401, there were remote file changes, and I tried to use "redeploy" from Vercel to pull the remote changes. However, the Vercel and Netlify deployments failed as they showed the old cache. 

When I pushed a new commit to the branch, the deployment was successful. @CharlieC3

**Comment by chresko** [comment]
@LakshmiLavanyaKasturi Can this be closed? Thanks!

**Comment by rafaelcr** [comment]
We should still write this automation. Now that we have automatic OpenAPI updates in the docs repo (thanks to https://github.com/hirosystems/docs/pull/525), we should just make sure that whenever a release is made in any API that we trigger the docs Vercel build again so the new API definitions are refreshed automatically.

**Comment by CharlieC3** [comment]
@rafaelcr I submitted three PRs to address this here:
https://github.com/hirosystems/stacks-blockchain-api/pull/1787
https://github.com/hirosystems/ordinals-api/pull/285
https://github.com/hirosystems/token-metadata-api/pull/192
