### ISSUE TITLE
Add a isRecursive meta tag to responses, and as a filter option?

### ISSUE THREAD

**Issue by janniks** [hirosystems/ordinals-api#124]
Idea, might not be efficient

---

- Index recursive inscriptions (scan for text inscriptions that include `/content/:iid` to other inscriptions)
- ? Allow filtering by this tag
- ? Add as a field in inscription response

Related: #123

**Comment by chresko** [comment]
@rafaelcr I'm onboard with this addition to the API if we're able to support it. Super useful for searching/filtering, and any consumers of the API who want to support this as well.

**Comment by rafaelcr** [comment]
@janniks can you point me to the code you currently use to detect recursion on inscription contents?

**Comment by janniks** [comment]
No code for this exists yet.
Basically the recursive inscription would be text/html (or a similar type, I think some svgs allow relative external elements)  which use a relative href/link to `/content/:iid` or any other link provided under [the recursion section of ord](https://docs.ordinals.com/inscriptions.html#recursion). So we would manually have to scan for those text occurrences (might be tricky for edge cases).
