### ISSUE TITLE
Unstable sort when ordering by genesis_block_height

### ISSUE THREAD

**Issue by jack-linden** [hirosystems/ordinals-api#162]
Reproduction: 
https://api.hiro.so/ordinals/v1/inscriptions?address=bc1patm6f65h7kvppjss2p0fh4na67um30z7dd6txtqxjzmrwv0tz9ss47mdlc&limit=60&offset=0

Result set is not always sorted consistently - leading to pagination issues.

**Comment by chresko** [comment]
How should I debug this @rafaelcr?

**Comment by jack-linden** [comment]
@rafaelcr I think its actually a caching issue and not related to pagination/sorting. See the below TS playground

This code paginates through the result set and pops each inscription_id into a set. The expected response set size should be 265 but instead varies (run several times in new incognito browsers or clear browser cache before each run). If you flip the "bypass_cache" flag to true (passes a Date.now() query param to the URL) it will give the accurate 265 response set size.

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAjgB2AfShAzmgexFxQG8AoZZAG2AFtgwAuZEAVzoCNoBuS5AjBglmrDtyh8qYAmDjUW7Lr345cbamFwt0WNRrABtALp8AvuXKhIsRCl3Y8B5BSrAAJi1xgooAOZSYspQiuIqVHDu7mrayN6+IAH8APTJyACCUQJgABbQyGhQBGjQYMB4qLisEBDutciccCTuAiDIAJ4EbFAZAAoAkshqhMQQ5BbkCETeDe1oTbiYCIh5yAC8yD5sEHzkTe0gCMgwbIdlRMcQYAg5mO5wcgAUgsJXocEAlCy9RQwkADwOYbTCAAPhcKTSACUIGhqHZkAByHJgMBobSpXQAOggAA84HQ4RAsVM6Ml7nJEcgAO6MHKbVaIMBseR9QYQEDuQjWfhTYhgIZ4EYkdaoalwRiXa45R4AAxRaIxyWxOWARSxuAIyQIUHcoHkuGSADcAIzJUC4BC+NDnYgAfki0TwuDWnAQJvmYDoADYYN6AKw5ADsAGsjWg0AArXC4ABMaAADDAcgAWEBwb1BjgAZgTAC8g1FvWBcWAAI64yN5uhQalGhNgPMAThjKaDdHc1AQADJaAwwGtvQnuy8RGsACSkUdXMwj3XQTCcdprPwcvDARacagEBAhzB5YB+FGTpfzGNLFYoO3IWXdsp0CAT0gAEQexJABGpjw+ZllyBYiKIr+HyBHyMwUnAOgYI4+AgqKcDipKwKjFi0ZEN+gQ4MyUBtBB5iWPshzHKcCC2gUcB+PqkCYLo37fL8G4QP8RoEB44KuMgYECvMq6YLgwB5hA7wSKKQ6BNQVwCEIIjCfkGwJuJkkyHI1AwQYsRKCJ8mgdMAoWlawA2sA0yiiAEDUsgADKVz-PE-ighhlhUO4BAQlQVBccgEFQXoQpwRsCESgKMBXDcdwPHAzzSVcIH8B5umCuomixECTiaCYooQVi+jJbs7nIKkyA-DuzoMigCDdDg4DkauUmJepcXHDqyCPJ5OUCoI9XJR8bn5QVaQAJpdD0hQlTG-g0AQlFHHkOCNW4xAGUZ0xYo6jztViHixflEz5cp8hqclmURVi+3UIEVDTgKADUGw8RAfECTs-BmDSqoSS1V3IP8myyAd7W4LFvLTAQElYtufiPPp1q2rgGpPbFEyFQAwvI1BlcRZzGW0MhxHIUDcRRVH+OQPFUQ9tEgUAA

**Comment by rafaelcr** [comment]
@jack-linden that behavior makes sense. The API is designed with "eventual consistency" in mind, which means that whenever we receive new data from a Bitcoin block we process it, store it in the DB, and immediately after run other background tasks that cache some results, stats, counts, etc. so we can respond to API calls faster. It's entirely possible that while you run the TS playground code a new block comes by or we finish one of these background tasks and that alters pagination results.

Also, the Bitcoin chain does re-org from time to time which means we occasionally need to delete and re-index some blocks to go back to the canonical chain tip. This would also alter pagination results.

**Comment by jack-linden** [comment]
I would understand if the user is actively receiving or sending inscriptions while these queries execute but this address's holdings have not changed in over a week and therefore there is no reason why the result set should ever be inconsistent. 

Is the API load balancing to multiple independent Postgres databases of which could be out of sync?

**Comment by rafaelcr** [comment]
Ok thanks, this is very helpful. I'll take a closer look at this sorting and get back to you @jack-linden

**Comment by chresko** [comment]
@rafaelcr Can I close this one? Thanks!

**Comment by rafaelcr** [comment]
@jack-linden this will be fixed on the next production deployment
