### ISSUE TITLE
[BRC-20] Add ticker search filter

### ISSUE THREAD

**Issue by janniks** [hirosystems/ordinals-api#164]
We could add a text filter for token tickers on the brc-20 endpoints.
![Screenshot 2023-07-21 at 14 35 20](https://github.com/hirosystems/ordinals-api/assets/6362150/417ecdff-761c-46ae-945c-c6083100bf6a)

**Comment by chresko** [comment]
Is this a filter or a search?

**Comment by chresko** [comment]
Great idea - marked as high impact.
