### ISSUE TITLE
Recent ordinal transaction (transfer) not registered by Hiro's ordinals api

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-api#166]
It is this ordinal `2918c6c57a8b414f304c1f0279386e13cc6f8a88aa1ed7137c44c2cb087040c2i0`
https://magiceden.io/ordinals/item-details/2918c6c57a8b414f304c1f0279386e13cc6f8a88aa1ed7137c44c2cb087040c2i0

it was transferred to a Hiro wallet three days ago but isn't displayed there because the Hiro ordinals API didn't pick it up. 

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/69675b2b-c947-4ce6-9631-535ea5334cf3)

https://ordinals.hiro.so/inscription/2918c6c57a8b414f304c1f0279386e13cc6f8a88aa1ed7137c44c2cb087040c2i0

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/76141b3d-5ca3-40c5-9621-21fe0749ebac)

Expected owner: https://magiceden.io/ordinals/wallet?walletAddress=bc1pfyly006xgqmvvc42n36ddk3zxy5zgftf7lr667cpvrlda5l3rz2q766x20

**Comment by 314159265359879** [comment]
perhaps related to: https://github.com/hirosystems/ordinals-api/issues/143

**Comment by chresko** [comment]
@rafaelcr Any idea what's up with this?

**Comment by rafaelcr** [comment]
Hi @314159265359879 thanks for the report. This does seem related to #143 , we're in the process of creating a new API deployment that will get rid of these issues. I'll keep you posted.

**Comment by smcclellan** [comment]
Hey @314159265359879, this will be fixed by the latest index, expected by Wednesday of this week.

**Comment by 314159265359879** [comment]
This issue has been resolved. Thanks @rafaelcr and @smcclellan!
