### ISSUE TITLE
API Load Testing for Ordinals API

### ISSUE THREAD

**Issue by smcclellan** [hirosystems/ordinals-api#170]
Our goal here is to determine, for our infrastructure:

What is our requests per minute (RPM) limit for the Ordinals API?

When we're ready to load test against staging, ping DevOps to complete this ticket:
https://github.com/hirosystems/devops/issues/1241

**Comment by smcclellan** [comment]
Waiting on the environment for this. ETA Monday latest to start this effort.

**Comment by timstackblock** [comment]
Orfinals API Load test first run - Aug 22nd after the environment was upgraded.

While running a test I noticed a large amount of 524 errors with a low amount of load, only 10 Vusers were used to run the test. After 20 mins CPU utilization spiked and the response time was extremely slow. I pulled Charlie in as I noticed only 1 cluster was getting all the traffic and he discovered the following.

> 
> I see the database CPU is maxing out. It’s using 3X more than it’s configured for. This is normally fine for short spikes, but not sustained usage. However, the ord-api deployment has very low resource usage, and isn’t even scaling out.
> These signs are pointing to the database being the bottleneck, most likely the queries.

> Is the statement_timeout parameter being set in the Ordinals-API session with the pg db? If not, I can create a ticket for that. The db in staging is being bogged down from queries taking a very long time (~1 hour)

You can follow along in the #team-ordinals channel for more information, we came to the conclusion that some optimizations and configuration changes had to be made and Rafael would push a fix up to resolve this problem.


<img width="1485" alt="Screen Shot 2023-08-22 at 12 55 37 PM" src="https://github.com/hirosystems/ordinals-api/assets/49165468/2ad83c7d-ce4a-4380-b557-d1d32d21a97f">

<img width="755" alt="Screen Shot 2023-08-22 at 12 47 07 PM" src="https://github.com/hirosystems/ordinals-api/assets/49165468/cb73191f-89d5-4ca3-96f1-9a3f22ab7101">

<img width="1238" alt="Screen Shot 2023-08-22 at 7 07 54 PM" src="https://github.com/hirosystems/ordinals-api/assets/49165468/f13abe5e-7f4b-4dba-8256-b1d943dada5b">
