### ISSUE TITLE
[BRC-20] Endpoint that streams BRC-20 events

### ISSUE THREAD

**Issue by fiftyeightandeight** [hirosystems/ordinals-api#171]
We will be releasing the first version of BRC20 on-chain indexer soon (see picture below). It requires a number of "validators" or "guardians" that validate BRC-20 events, before the on-chain indexer updates its record.

If Hiro Ordinals API can add an endpoint that streams BRC-20 events, then we can create a validator to subscribe to that endpoint, which will allow Hiro indexer to participate in validating BRC-20 events for our on-chain indexer.

We are currently working with a few other off-chain indexers and it will be great if we could work with you too.

The on-chain indexer repo is https://github.com/alexgo-io/brc20-indexer-v1.

![telegram-cloud-photo-size-5-6201746043587115062-y](https://github.com/hirosystems/ordinals-api/assets/443225/f9d1d99a-6e8a-4f79-b946-51b4f389a8a5)

**Comment by chresko** [comment]
We're actively developing this on our end. Great to see a similar initiative. Thanks!
