### ISSUE TITLE
After successful registration, chainhook did not scan the inscription and send it to oridnals-api

### ISSUE THREAD

**Issue by pupudaye** [hirosystems/ordinals-api#182]
The chainhook only has these logs, and it did not send any inscription data to the ordinals-api after running to catch up with the latest block!

ordinals-api:  origin/master
chainhook: v1.0.0

chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767479,\"number_of_blocks_scanned\":50,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:04:22.753126507Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767529,\"number_of_blocks_scanned\":100,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:04:32.930928566Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767579,\"number_of_blocks_scanned\":150,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:04:44.210319327Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767629,\"number_of_blocks_scanned\":200,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:04:51.922564889Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767679,\"number_of_blocks_scanned\":250,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:05:01.006710377Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767729,\"number_of_blocks_scanned\":300,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:05:13.716744987Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767779,\"number_of_blocks_scanned\":350,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:05:24.122661652Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767829,\"number_of_blocks_scanned\":400,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:05:34.554727491Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767879,\"number_of_blocks_scanned\":450,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:05:42.922632834Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767929,\"number_of_blocks_scanned\":500,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:05:51.182625197Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":767979,\"number_of_blocks_scanned\":550,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:06:00.967407003Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":768029,\"number_of_blocks_scanned\":600,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:06:06.785667332Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":768079,\"number_of_blocks_scanned\":650,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:06:17.317386571Z"}
chainhook-node  | {"msg":"Updating predicate predicate:e557f21a-88cc-4c14-996c-0d4dfd8ef8ee status: {\"scanning\":{\"current_block_height\":768129,\"number_of_blocks_scanned\":700,\"number_of_blocks_sent\":0,\"number_of_blocks_to_scan\":35168}}","level":"INFO","ts":"2023-08-11T03:06:29.32278952Z"}

**Comment by smcclellan** [comment]
Closing for now -- if the above comment does not resolve this, please reopen.
