### ISSUE TITLE
Get BRC-20 Balances of Wallet at a given block-height

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/ordinals-api#185]
returns BRC-20 token balances of a wallet at the start of the given block-height
example: https://api.bestinslot.xyz/v3/brc20/balance_on_block?block_height=802389&pkscript=0014cd6cccc69331a96ea0fe0fa5d1d184a811979a8b

**Comment by chresko** [comment]
Estimated lift @rafaelcr ?

**Comment by smcclellan** [comment]
Follow-up @janniks, `address` is enough for now, but we want to add `pkscript` in the future.
