### ISSUE TITLE
Returning content of inscription

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/ordinals-api#19]
Will it be possible to query the contents of an inscription?

On another API this just links to `ordinals.com/content/ID`.

At the very least it would be awesome to access text to start with - thinking protocols like [sats.id](https://sats.id) and [inscribe.news](https://inscribe.news).

**Comment by rafaelcr** [comment]
Sure, this is already possible with this endpoint: https://docs.hiro.so/ordinals#tag/Inscriptions/paths/~1ordinals~1v1~1inscriptions~1%7Bid%7D~1content/get
Unless I misunderstood your question?

**Comment by whoabuddy** [comment]
Nope - I think when I looked at the docs it wasn't there, but it's working for me now, thanks!
