### ISSUE TITLE
Some cursed inscriptions are missing in the latest index

### ISSUE THREAD

**Issue by timechainz** [hirosystems/ordinals-api#192]
**Describe the bug**
Some cursed inscriptions are not showing up in the latest index.  All OCM dimensions inscriptions are not found, for example.

https://api.hiro.so/ordinals/v1/inscriptions/45a3b9772d13e8f8d88c73521d313d42c021783a69cb32bc5a085b5dba37c5cfi0
https://ordinals.com/inscription/45a3b9772d13e8f8d88c73521d313d42c021783a69cb32bc5a085b5dba37c5cfi0

**To Reproduce**
Attempt to retrieve inscription metadata for a cursed inscription (e.g. 45a3b9772d13e8f8d88c73521d313d42c021783a69cb32bc5a085b5dba37c5cfi0)

**Expected behavior**
The inscription should be found because it was previously indexed by hiro and is recognized on ordinals.com.

**Screenshots**
``` 
{"error":"Not found"}
```

**Additional context**
Add any other context about the problem here: 
```
{"server_version":"ordinals-api v1.0.0-beta.16 (beta:f7b3cf4)","status":"ready","block_height":804943,"max_inscription_number":26697209,"max_cursed_inscription_number":-104473}
```

**Comment by 314159265359879** [comment]
Thanks for reporting!
I see this is created on June 13th, I wonder if it is related to #193: a couple of other inscriptions that were displayed up until recently.  I do know a new index recently went live, perhaps these were missed somehow. 

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/bbab10ab-3943-4b56-8106-65826e3c49c0)

**Comment by chresko** [comment]
@rafaelcr Does the recent re-indexing resolve this?

**Comment by 314159265359879** [comment]
Is this related?

A user noticed that some cursed inscription numbers are different between ord.io and ordinals.hiro.so compare this one for example:

https://ordinals.com/inscription/bdb2456773d1a65c7d47f70116f058dec9ae9dfaf56a0cd6ea530d76124b7107i0

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/dedd2562-31b1-4105-ab03-e4ff014156f0)

https://ordinals.hiro.so/inscription/bdb2456773d1a65c7d47f70116f058dec9ae9dfaf56a0cd6ea530d76124b7107i0

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/e774da99-f731-4196-9991-2b0a7f872b69)
