### ISSUE TITLE
Ordinals API query for genesis block returns total:0 but there are results in the array

### ISSUE THREAD

**Issue by bitlodo** [hirosystems/ordinals-api#245]
**Describe the bug**
Ordinals API query for some genesis blocks always returns a "total: 0", but there are results. With a total equals 0, it´s not possible to paginate the results.

**To Reproduce**
1. Go to https://api.hiro.so/ordinals/v1/inscriptions?genesis_block=806117
2. View the results:  {"limit":20,"offset":0,"total":0,"results":[{"id":"ca2a8abcdfd...
3. Change the genesis_block values
4. Some blocks will show the correct total, but mostly between 806117 and 807269 will display total: 0

**Expected behavior**
All blocks should return the correct total value

**Comment by rafaelcr** [comment]
Fixed by https://github.com/hirosystems/ordinals-api/pull/248
