### ISSUE TITLE
Request: Remove ordinals-api ingestion POST method from needing a UUID format

### ISSUE THREAD

**Issue by mefrem** [hirosystems/ordinals-api#246]
Currently, a developer can only deliver payloads to the Ordinals API (from e.g. ordhook) by making a POST request with a URL that ends in a UUID, e.g. something like http://localhost:3000/api/c44a3e4c-6200-11ee-8c99-0242ac120002

This wasn't intuitive nor is it documented clearly, either in ordhook or the ordinals-api READMEs. 

Request/solution: Can the workflow be such that a developer can deliver payloads to an arbitrarily-set, human-readable URL?

**Comment by rafaelcr** [comment]
Fixed in #277
