### ISSUE TITLE
Get inscriptions created on a given block

### ISSUE THREAD

**Issue by fboucquez** [hirosystems/ordinals-api#257]
Hi team, is there a way to know the created inscriptions of a given block?

I was expected to be in the transfer API, for example, https://api.hiro.so/ordinals/v1/inscriptions/transfers?block=767430 to include the [first](https://ordinals.hiro.so/inscription/6fb976ab49dcec017f1e201e84395983204ae1a7c2abf7ced0a85d692e442799i0) minted inscription, the first activity.

**Comment by rafaelcr** [comment]
Hi @fboucquez you're looking for the `genesis_block` filter in the inscriptions endpoint: https://api.hiro.so/ordinals/v1/inscriptions?genesis_block=767430

**Comment by fboucquez** [comment]
Thanks! missed that one 🤦
