### ISSUE TITLE
Deploying its own instance

### ISSUE THREAD

**Issue by 0xWhiteleaf** [hirosystems/ordinals-api#26]
First of all thank you for this API, extremely useful and will save time for many people in the ecosystem 👌 

I tried this weekend to get an instance up _(i.e ordinals-api x chainhook)_ on our project's infrastructure but without success, several errors on the chainhook side appeared and quite complicated to solve without more documentation. Do you think it's possible to release more detailed documentation on how to run your own instance (I think it's already planned, but I wanted to share my feedback)?

Thanks a lot!

**Comment by diwakergupta** [comment]
> Do you think it's possible to release more detailed documentation on how to run your own instance (I think it's already planned, but I wanted to share my feedback)?

Thanks @0xWhiteleaf! Just to set expectations for you and anyone else with a similar ask: we totally understand there are situations in which one might want to run their own instance on-premise. Unfortunately given our team size and other competing priorities, we can only focus on our hosted instance at this time -- technical support & docs for running your own instance would be on a best-effort basis.

I'd love to understand your use-case and specifically why using Hiro's hosted instance is not an option for you. Happy to take that conversation offline  - perhaps we can connect on Discord or over email?

**Comment by 0xWhiteleaf** [comment]
Thanks for your response @diwakergupta. Totally understandable not a problem 👍 
Feel free to add me on Discord: 0xWhiteleaf#0591
