### ISSUE TITLE
Is API Key required?

### ISSUE THREAD

**Issue by fboucquez** [hirosystems/ordinals-api#270]
Hi team, awesome job.

It seems like now the api key is required, I get Too Many requests, not allowing any calls.

https://api.hiro.so/ordinals/v1/

I have completed the form and waiting for a key. Should a limited/free api key be documented?

**Comment by rafaelcr** [comment]
Hi @fboucquez I believe you already received the key so I'm closing this issue. Feel free to re-open if you need further assistance.

**Comment by fboucquez** [comment]
Thank @rafaelcr just reporting because no call was possible without the key. Now its fixed
