### ISSUE TITLE
Return inscriptions by owner address

### ISSUE THREAD

**Issue by yknl** [hirosystems/ordinals-api#30]
Would be great if the API returns all ordinals owned by specified Bitcoin addresses. This is useful for wallets.

**Comment by muncheruniverse** [comment]
+1 this would be a killer feature for us

**Comment by rafaelcr** [comment]
Hi @yknl this is already possible, for example: https://api.hiro.so/ordinals/v1/inscriptions?address=bc1pyjg09s03v60phe6dxw33f5dn6sd3q72zk024eqq50ef8de0g7d7shk0s63

**Comment by rafaelcr** [comment]
You can also provide more than 1 address if a wallet wants to keep track of several of them. Closing this as completed but please reopen if you have more questions.

**Comment by muncheruniverse** [comment]
Epic
