### ISSUE TITLE
Incorrect "Owned By" data for certain inscriptions

### ISSUE THREAD

**Issue by brandonmarshall-tm** [hirosystems/ordinals-api#302]
Quantum Cats completed their mint today and sent inscriptions to their holders. These inscriptions are not appearing in Leather wallet Collectibles at the moment, I believe because the "Owned By" wallet address is incorrect.

Example:
https://ordinals.hiro.so/inscription/deff9507e7dfd068b6b2facf38df83c6e34ba58e164d6351e64c390f89b06fc1i562

Hiro reports this inscription is owned by bc1p7xf7dnzkejj47s2706l2tqq5a33zk0vlpjgg93djleagp3my6xes68jznt

Other indexers report this inscription is owned by bc1pdfmqcefzn3t28lzdvv8s5kv7t25pnq49t4sqtnkyujt5kytt4njqydkqup (which is the correct owner)

https://ordinals.com/inscription/deff9507e7dfd068b6b2facf38df83c6e34ba58e164d6351e64c390f89b06fc1i562
https://www.ord.io/53789502
https://ordiscan.com/inscription/53789502

Confirmed on multiple Quantum Cats: https://ordinals.hiro.so/inscription/4b31771df21656d2a77e6fa18720a6dd94b04510b9065a7c67250d5c89ad2079i260

This will likely be fixed by issue #294 but it seemed a little different, since in this case the inscription number is actually correct but the reported owner is wrong.

**Comment by rafaelcr** [comment]
Hi @brandonmarshall-tm this issue will be fixed by https://github.com/hirosystems/ordinals-api/issues/294, marking as duplicate
