### ISSUE TITLE
Wrong block hash at block 827853 and 818038

### ISSUE THREAD

**Issue by alexqrid** [hirosystems/ordinals-api#304]
**Describe the bug**
There's a block hash inconsistency in the api. After the block `827853` was orphaned, the new block of the same number wasn't processed correctly.
Ordinals api currently displays `00000000000000000002c7de4016a0d09a47c19075cb73947e7f66e3461efd27` for the block, but its actual hash is  `00000000000000000003e9ce9f143383317a9f6f4fd09bd0ee37a8053dfbf00f`
Block#  827853

**To Reproduce**
```shell
$ curl --location 'https://api.hiro.so/ordinals/v1/brc-20/activity?block_height=827853'|jq
{
    "limit": 60,
    "offset": 0,
    "total": 5788,
    "results": [
        {
            "operation": "mint",
            "ticker": "eorb",
            "inscription_id": "02b7707e6eefbcfe778c70fd2beb7f73d4b37d040013ed5a7b9945e411fe102di0",
            "block_height": 827853,
            "block_hash": "00000000000000000002c7de4016a0d09a47c19075cb73947e7f66e3461efd27",
            "tx_id": "02b7707e6eefbcfe778c70fd2beb7f73d4b37d040013ed5a7b9945e411fe102d",
            "location": "02b7707e6eefbcfe778c70fd2beb7f73d4b37d040013ed5a7b9945e411fe102d:0:0",
            "address": "bc1qmaux7l33nz4vtxf3pj3tz92mcey8nlrffuvrfs",
            "timestamp": 1706474126000,
            "mint": {
                "amount": "10.000000000000000000"
            }
        },
......
}
```
The same thing is with the block 818038 
`00000000000000000003d017a9a751467965e1e2ed0f6d1fbbef0ceecf6ed9b5` vs. `000000000000000000029afbc6cbd660df5548a90ca9202e80866c5c680f29e4`
**Expected behavior**
Seems like `ordinals-api` didn't processed fork correctly.

**Comment by rafaelcr** [comment]
Thanks for reporting @alexqrid . This will be fixed with the reindexing in #294
