### ISSUE TITLE
Chainhook node not available, retrying 

### ISSUE THREAD

**Issue by echoWeb3** [hirosystems/ordinals-api#31]
Hello everyone, I am new to BTC, sorry to ask you some basic questions. I have correctly installed chainhook as chainhook requires, but how should I enable chainhook?
The chainhook document says that a predicate is needed. Do you have a predicates template related to the ordinal number of Bitcoin? If so, can you let me learn it?
Also can you tell me how to start the chainhook?
Thanks!

**Comment by rafaelcr** [comment]
Hi @echoWeb3 sorry for the late response, we're currently working on getting the Chainhook repo up to speed with the latest verison of our ord indexer, so we'll be able to provide you with more info soon

**Comment by rafaelcr** [comment]
Hi @echoWeb3 please take a look at our new separate repo for Ordinals indexer `hord` here https://github.com/hirosystems/hord
