### ISSUE TITLE
Indexing issue BRC20 inscriptions

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-api#329]
**Describe the bug**
This inscription is displayed as still owned by the address prior to the last transaction. 
https://ordinals.hiro.so/inscription/4035f2bd8d86459346dfbc8e390d61b35761f80efdbfc7b36b5b79a75b17c7e5i0

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/539d0202-9779-4e24-8306-08e14a9184a3)

As can be seen here other indexers do display it transferred to bc1p2f6pttsec30rpkl54hefzfm4fnu5v0p3gels4kxcrv32cue9kmcswjdqz9
https://ordiscan.com/address/bc1p2f6pttsec30rpkl54hefzfm4fnu5v0p3gels4kxcrv32cue9kmcswjdqz9/brc20
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/af67ce36-5581-4723-9089-f91b7ec3ad2e)
so does [bestinslot.xyz](https://bestinslot.xyz/bc1p2f6pttsec30rpkl54hefzfm4fnu5v0p3gels4kxcrv32cue9kmcswjdqz9#type=brc20)

Transaction ID https://mempool.space/tx/87e3fa5b0f6ac5309ea5240709f70ae485acfcb6ca44e8c93271d698fe7352b4
Address bc1p2f6pttsec30rpkl54hefzfm4fnu5v0p3gels4kxcrv32cue9kmcswjdqz9
Block#  833428
Time stamp 2024-03-06 18:01 (3 days ago)
--

A similar issue
https://ordinals.hiro.so/inscription/2250b3130684274b2a68af536c02bbd7cda8492a908f0414b2330b90b3083ecai0

Is [transferred to](https://mempool.space/tx/6b3ebaaf74f82a185000a2e74ebadc2559eb0e54d852b8d8e07bec279fae9fb1) bc1plqjh3g28rd4wsflc0zadm7ekrc7gdjn37lpv2nx6hef2u4kv252q0wfms6 but displayed as still owned by bc1p6q67lz2wam5ua42dz5474lsyker9lwav2xc2fge86wuf4taxntvspvlw4g

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/50c4f8da-7614-4723-a387-c2d83d8a81ec)

Transaction id: https://mempool.space/tx/6b3ebaaf74f82a185000a2e74ebadc2559eb0e54d852b8d8e07bec279fae9fb1
Address 
Block 833664
Timestamp 2024-03-08 03:50 (1 day ago)
--

Can the issue be resolved with this data?

**Comment by rafaelcr** [comment]
Thanks for your report @314159265359879 . This is now fixed and deployed. Please let me know if you notice any more problems.

**Comment by 314159265359879** [comment]
Thanks for the quick fix!
