### ISSUE TITLE
Inscriptions inscribed on the same sat showing in hiro indexer but not ordinals.com

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-api#332]
**Describe the bug**
Maybe this is not a bug, I am not sure so please make your own assessment. 

A user reported minting 12 taproot wizards. These show in marketplaces and ordinals.com and are transferable via Leather. There are another 42 showing up too in Leather and ordinals.hiro.so. 

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/d1ca2bed-f53f-48c6-9f91-a3555358d940)

Here are 3 that are under the users wallet on ordinals.com

https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i0
https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i1
https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i2

Here are 3 that are showing in my leather wallet and on [ordinals.hiro.so](https://ordinals.hiro.so/inscriptions?a=bc1ptxyxg6jprmf46nral0g0rdcg6cez4hyr69769kn8pnzekdfkda2suw99u5) but NOT under my address on ordinals.com

https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i19
https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i18
https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i13

For note, of the 12 I inscribed, all function fine for sending and marketplace. 

Investigating some of the other 42 I noticed they are in the same output and have the same offset. It looks like they are all inscribed on the same sat. Is that an indexing mistake or true?

That means they are inscribed on the first sat of this UTXO:
[195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21](https://mempool.space/tx/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21)
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/7ad386f5-6a33-448f-83a7-ce60d1dd2602)

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/58b71299-8551-4ea3-ae67-bffde70d99a7)

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/b5021bc8-b207-4163-9873-0d979f073896)

These 42 are not transferable because Leather doesn't support sending inscription UTXO's with multiple inscriptions yet. 
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/e7990e43-bde3-4222-8dba-5a58f82ee8ae)

Transaction ID 195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21
Address https://ordinals.hiro.so/inscriptions?a=bc1ptxyxg6jprmf46nral0g0rdcg6cez4hyr69769kn8pnzekdfkda2suw99u5
Block#  831103
Time stamp 2024-02-19 09:52

**Comment by rafaelcr** [comment]
@314159265359879 I don't think there's an issue here, I've checked these 3 sample inscriptions and they both show the same owner on both our Explorer and ordinals.com:

https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i19
https://ordinals.hiro.so/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i19

https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i13
https://ordinals.hiro.so/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i13

https://ordinals.com/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i2
https://ordinals.hiro.so/inscription/195857e315105f11c45a1184a27c832f902dd76764a136eb4a7e6495ebbe3d21i2

Please feel free to reopen if you notice something else, though. Thanks!
