### ISSUE TITLE
Runes indexing 

### ISSUE THREAD

**Issue by Morgandri1** [hirosystems/ordinals-api#339]
**Is your feature request related to a problem? Please describe.**
Not really? I would like to ask for Runes to be added to the ordinals api and indexer.

**Describe the solution you'd like**
runes should be indexable and parallel to inscriptions and brc-20

**Comment by bobbychen** [comment]
And what is this going on?

**Comment by rafaelcr** [comment]
hello everyone, thanks for your patience, we're working hard on this at the moment so stay tuned for news 👍🏻
