### ISSUE TITLE
Ordinals API database storage requirements

### ISSUE THREAD

**Issue by endangurura** [hirosystems/ordinals-api#340]
I tried to setup Ordinals API database using [ordinals-api-pg-15-latest.dump](https://archive.hiro.so/mainnet/ordinals-api-pg/ordinals-api-pg-15-latest.dump) file 

`pg_restore -d ordinals_api -U ord -C /btc/ordhook/ordinals-api-pg-15-latest.dump` I got this error `ERROR:  could not write to file "base/pgsql_tmp/pgsql_tmp4114331.36.fileset/0.1": No space left on device`

I run out of space on a 256GB volume 

What 's the disk space requirements for Ordinals API DB.

**Comment by smcclellan** [comment]
We recommend 1TB for this. Changing this ticket to be about updating [docs](https://github.com/hirosystems/ordinals-api?tab=readme-ov-file#system-requirements).
