### ISSUE TITLE
Enable to gap detection when ordinals-api is streaming blocks from ordhook

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-api#342]
**Describe the bug**
This inscription is not displayed in the ordinals explorer
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/d9af24a3-22ca-41d0-a9ec-dfa7d6a08dad)

https://ordinals.hiro.so/address/bc1ph03a7qkx3d2x8lslsukxxefmgjjtzsej3fvmdzyy5u8hcn4uyafql979l6 

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/f8b21720-ffea-40c1-bd14-489a284eb735)

When I check it here I do see it associated with their wallet so it is definitely in there https://ordiscan.com/inscription/67758714
https://www.ord.io/67758714 

Related transaction https://mempool.space/tx/9e3d1d1a2d5f4052190bc2e1658b9982d130c9f6cd0a57fbd5c7af8e7c4d958d
‎2024-04-07 22:08 (15 hours ago)

**Comment by lgalabru** [comment]
@314159265359879 Thanks for the nudge, this inscription should now be visible.
I'll re-purpose this issue, we need to re-enable to gap detection when ordinals-api is streaming its content from ordhook.
