### ISSUE TITLE
Incorrect genesis tx_id for cursed inscriptions 

### ISSUE THREAD

**Issue by sam-xyz** [hirosystems/ordinals-api#353]
For this endpoint - https://docs.hiro.so/ordinals/specific-inscription , for cursed inscriptions, the genesis tx_id is incorrect. 

e.g. for insciption number -1 , the mint tx should be 617b02026b7d56c85a41c07ebfd67a1186f0888fd07c59428f11b1b9cdf6a84c - https://ordinals.com/inscription/617b02026b7d56c85a41c07ebfd67a1186f0888fd07c59428f11b1b9cdf6a84ci0 but the response  from the endpoint is bdda0d240132bab2af7f797d1507beb1acab6ad43e2c0ef7f96291aea5cc3444 (another tx in the same block) 

As a result of this, the transfers per block endpoint https://docs.hiro.so/ordinals/transfers-per-block , does not show the cursed inscription mint transactions. Only the first transfer after the mint is available. For example, 617b02026b7d56c85a41c07ebfd67a1186f0888fd07c59428f11b1b9cdf6a84c (inscription number - 1) in block 838140 doesnt show up in the response

**Comment by lgalabru** [comment]
Thanks for the feedback @sam-xyz! I'm moving this issue to the ordinals-api for better tracking.

**Comment by rafaelcr** [comment]
This will be fixed in the new index we're currently building. We'll release it into production as soon as it's ready.

**Comment by rafaelcr** [comment]
This is fixed. Thanks for your patience.
