### ISSUE TITLE
Hiro indexer seems off causing a different inscription number than ordinals.com/ord.io

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-api#358]
**Describe the bug**
It looks like the inscription number is off on hiro indexer Inscription #70927565
https://ordinals.hiro.so/inscription/afd0b0e6c09b2475d6e639713aa789ced71155c55446433d83b5c65e2aaefe35i0

Via ordinals.com I see this number:
Output 
https://ordinals.com/output/afd0b0e6c09b2475d6e639713aa789ced71155c55446433d83b5c65e2aaefe35:0 
showing: 
instead of Inscription 70936333
https://ordinals.com/inscription/afd0b0e6c09b2475d6e639713aa789ced71155c55446433d83b5c65e2aaefe35i0 

Transaction ID afd0b0e6c09b2475d6e639713aa789ced71155c55446433d83b5c65e2aaefe35

Address bc1pg3u6pxvp0v3ywjahwy9hqn488s9dgeshs0vp455gzue5lgqzra7qtj04zl
Block#  844406
Time stamp 2024-05-21 08:59 (1 day ago)

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/4e7ba6e6-bbcb-4f4e-8c59-c568022b9254)
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/497ecfa7-76bf-4dd3-b3af-106f1da687a6)

**Comment by 314159265359879** [comment]
I have seen more cases like this
https://ordinals.hiro.so/inscription/fd66fc9949200ccecffbaf03dcb9ec52db4016a59a563b86ab84a10d3493383bi0
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/d6930502-541b-4032-851e-855765f47935)

why is the image not displayed here?

expected number:
https://ordiscan.com/inscription/70641382
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/49878a42-b62c-4cfc-ba0c-cf78a5bf673d)

**Comment by markmhendrickson** [comment]
Curious if there are any updates here?

**Comment by rafaelcr** [comment]
hi @markmhendrickson @314159265359879 we've been rebuilding a new index that fixes these discrepancies, I'll let you know as soon as it's live

**Comment by rafaelcr** [comment]
This is fixed. Apologies for the delay!
