### ISSUE TITLE
Inscriptions not appearing for an address

### ISSUE THREAD

**Issue by ECBSJ** [hirosystems/ordinals-api#383]
This address owns inscriptions as evident in the Ordiscan explorer:

https://ordiscan.com/address/bc1pqzz4estur454xx84394h5x2200nx5v6ky9qnw4tmkz4glgjnykusggzuyw

But the Hiro Ordinals API is not returning anything:

https://api.hiro.so/ordinals/v1/inscriptions?address=bc1pqzz4estur454xx84394h5x2200nx5v6ky9qnw4tmkz4glgjnykusggzuyw

**Comment by smcclellan** [comment]
This has been resolved with an update.
