### ISSUE TITLE
Inscription not found

### ISSUE THREAD

**Issue by LRam10** [hirosystems/ordinals-api#384]
**Describe the bug**
Inscription da8ab9973cfec23637c021318e9def74abc920c5cb6d7b0bf524157833b90efbi0 not found

Transaction ID :da8ab9973cfec23637c021318e9def74abc920c5cb6d7b0bf524157833b90efb

Time stamp

**To Reproduce**
1. Go to 'https://ordinals.hiro.so/'
2. Search for 'da8ab9973cfec23637c021318e9def74abc920c5cb6d7b0bf524157833b90efbi0'
3. No data is found

**Expected behavior**
Here's the inscription https://ordinals.com/inscription/da8ab9973cfec23637c021318e9def74abc920c5cb6d7b0bf524157833b90efbi0

**Comment by rafaelcr** [comment]
API was behind chain tip at the time but now it's resolved
