### ISSUE TITLE
Inscription ordering and stats endpoints for  Explorer

### ISSUE THREAD

**Issue by saralab** [hirosystems/ordinals-api#4]
1. Sort/Filter default view or search results by content type and Sat rarity

  - **Content Types:**
  
    -       Image
    -       Video
    -       Audio
    -       Text
    -       Binary/Other

  - **Rarity**
  

      - common: Any sat that is not the first sat of its block
      - uncommon: The first sat of each block
      - rare: The first sat of each difficulty adjustment period
      - epic: The first sat of each halving epoch
      - legendary: The first sat of each cycle
      - mythic: The first sat of the genesis block

**Comment by rafaelcr** [comment]
Done
