### ISSUE TITLE
API endpoint giving last ordID in existence

### ISSUE THREAD

**Issue by grdddj** [hirosystems/ordinals-api#43]
It would be nice to have `ordinals/last_id`, so users could quickly get this info.

Currently, the process involves querying the `inscriptions` endpoint, which can be quite slow. E.g. 
```
XXX = 1_000_000
response = GET "inscriptions?limit=1&from_number=XXX"
total = response["total"]
highest_id = XXX + total
```

Quickly looking at https://github.com/hirosystems/ordinals-api/blob/develop/src/api/routes/inscriptions.ts, it seems like just adding a new route with returning the number of documents (or the max(id)) would do the trick. But please correct me if I am wrong :)

**Comment by rafaelcr** [comment]
Hi @grdddj you can look at the `max_inscription_number` if you query the status endpoint: https://api.hiro.so/ordinals/
```json
{
  "server_version": "ordinals-api v0.1.0-beta.6 (beta:ab4c3e3)",
  "status": "ready",
  "block_height": 786826,
  "max_inscription_number": 1602514
}
```
Let me know if you have further questions
