### ISSUE TITLE
ordinal api #513871 - unable to locate 

### ISSUE THREAD

**Issue by Faiwee** [hirosystems/ordinals-api#44]
Hi,

I inscribed ordinal #513871 on 18 March 2023 completed 19 March 2023 https://mempool.space/tx/3386f95852272610007e6ce0021dd0d5e84f32fa92aea3da3fc4baf9570a9c2d
https://ordinals.hiro.so/inscription/3386f95852272610007e6ce0021dd0d5e84f32fa92aea3da3fc4baf9570a9c2di0

There are 3 transactions in my hiro wallet related to the inscription

https://mempool.space/tx/37a5c34df223af2a3947865f4e32779f4fc577430a37ee4984ca6f6a0ed8f07b
https://mempool.space/tx/54f07599d14d806cac52d99a028cf7c338131ba2a3fcaca2cb8d6ad3c19ca6fb  
https://mempool.space/tx/9243710a49c26c21151017fd55121e0c1b58793af86eb3dec962e2bde8b3a9c7

My hiro btc wallet address is bc1q97jst3kxw8vl6yh0gv8tk4r7mmjlskphtsszyu
and my gamma.io ordinal wallet address is bc1p6lsaxplm5jvs7xk0pzs5qtg9anq0gwg623z4z65keh7p0389dt4q6u02lr 

it appears that my inscription is recorded as being inscribed by 
(https://ordinals.hiro.so/address/bc1p35dnr2ks4n7zqwvzz5a3t4xuv8qpk734h23gctvhnzqhxpq9j5as2czu3u)
and my ownership details are still clarifying .. "OWNED BY | coming soon hirosystems/ordinals - api#23"

I guess this is still in beta stage and it is a matter of patience?
Please advise and thank you
Rosemary

**Comment by rafaelcr** [comment]
Hi @Faiwee yep, correct ownership display is part of the next update to the Ordinals API we're working on right now. See issue #23 
We're going to be finishing this work very soon. Stay tuned.

(Closing as duplicate)
