### ISSUE TITLE
feature: support for BRC-20 tokens

### ISSUE THREAD

**Issue by diwakergupta** [hirosystems/ordinals-api#49]
Relaying from a builder in the ecosystem: "What we need from the API is a route for address balance of BRC-20 tokens. The balance of tokens is the result of ordinals inscription and transfers events. A nice to have would be a transaction history API."

**Comment by markmhx** [comment]
We'd apply it here in the wallet https://github.com/hirosystems/wallet/issues/3629

**Comment by markmhx** [comment]
UniSat's indexer is now open-sourced and perhaps worth a look re: this functionality https://twitter.com/unisat_wallet/status/1654136995210223616

**Comment by diwakergupta** [comment]
To clarify, what their indexer does is given _pre-processed data_ from Bitcoin in a [very specific format](https://github.com/unisat-wallet/libbrc20-indexer/blob/main/model/model.go#L11), it can build up state on BRC-20 tokens and presumably compute things like available supply through transfers and such.

**Comment by igorsyl** [comment]
I believe publishing a BRC-20 spec similar to https://docs.ordinals.com/ will help cement the BRC-20 protocol as an authoritative standard.

**Comment by fiftyeightandeight** [comment]
Hi all, fyi, we are currently using Bestinslot.xyz indexer (https://docs.bestinslot.xyz/reference/api-reference/brc-20).

**Comment by rafaelcr** [comment]
Hello everyone. The current work for BRC-20 indexing is being tracked in PR https://github.com/hirosystems/ordinals-api/pull/78. The initial plan is to support the following endpoints:
* `/ordinals/brc-20/tokens`
    Return paginated token information (ticker, max, limit, supply)
* `/ordinals/brc-20/tokens/:ticker`
    Return token info for a single ticker (all details + total holders)
* `/ordinals/brc-20/tokens/:ticker/events`
    Return event history for a single ticker
* `/ordinals/brc-20/balances/:address`
    Return balance for an address (optionally filtered by 1 or more tickers) giving available balance, transferrable balance, overall balance

Are there any additional endpoints you'd like to see supported?
