### ISSUE TITLE
API gives a wrong offset value for some ordinals

### ISSUE THREAD

**Issue by kuba-neoswap** [hirosystems/ordinals-api#54]
For some ordinals, API gives a big offset value like `435509929`, while ordinals.com shows offset `0`.

Example:
https://api.hiro.so/ordinals/v1/inscriptions/23198d6656ae23a9313eb3c2fffc8e6179e95905b92a042813feb705b6aeb1c5i0
https://ordinals.com/inscription/23198d6656ae23a9313eb3c2fffc8e6179e95905b92a042813feb705b6aeb1c5i0

A lot more ordinals like this are in this wallet: https://api.hiro.so/ordinals/v1/inscriptions?address=bc1ppmhxm8myvy55547ee4gyjv5ewzms4hrnhvpfg2z4el68as5f65vsskhg0y

It seems that the issue impacts only ordinals that haven't been transferred yet, i.e. `tx_id == genesis_tx_id`

**Comment by rafaelcr** [comment]
hi @kuba-neoswap thanks for the report this is a known issue that we're currently resolving cc @lgalabru

**Comment by kuba-neoswap** [comment]
Hey, just to let you know: the issue still exists.

Same example as before:
https://api.hiro.so/ordinals/v1/inscriptions/23198d6656ae23a9313eb3c2fffc8e6179e95905b92a042813feb705b6aeb1c5i0
https://ordinals.com/inscription/23198d6656ae23a9313eb3c2fffc8e6179e95905b92a042813feb705b6aeb1c5i0

A lot more ordinals like this are in this wallet: https://api.hiro.so/ordinals/v1/inscriptions?address=bc1ppmhxm8myvy55547ee4gyjv5ewzms4hrnhvpfg2z4el68as5f65vsskhg0y

**Comment by lgalabru** [comment]
The data is looking good but there could be an issue in the "presentation" layer. Looking at the `parseDbInscriptions` function: we're using the `offset` (coming from `ordinal_offset`, chainhook side) to the location, which is incorrect - @rafaelcr.

**Comment by kyranjamie** [comment]
Noticing that this is causing issue for Hiro Wallet users. We prohibit sending non-zero sat index offsets currently, so this causes false positives.

**Comment by 314159265359879** [comment]
Perhaps this will help track down the issue. 
An example, freshly minted:
Inscription number 6992438
In output: [d0d8ecbdb0fbd03fd90d1c0e42756f236b2165466f655f7379f1ab000eb71fc8:0](https://mempool.space/tx/d0d8ecbdb0fbd03fd90d1c0e42756f236b2165466f655f7379f1ab000eb71fc8)

In offset somewhere in the 129 million is an impossible offset when the output only has 546 sats in it (max offset is 545). 
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/20c8f48e-23fb-4880-9aa8-518a8f044402)

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/374ce472-530e-4bc3-878b-e1f0823fb085)

![image](https://github.com/hirosystems/ordinals-api/assets/33360391/4301390e-4081-4e6f-be67-58c18d91439b)

Another example, where explorer.hiro.so displays the right offset after the ordinal is transferred (one or twice?).
Inscription number  6861317
https://ordinals.hiro.so/inscription/8c4b0980f30b1a5faec0f252d38d3f68e4a97019655367d1c16b9867ddb66617i0 This was displayed a similarly high offset (in the millions) earlier today, inconsistent with the 10k output it is in. 

Then it was transferred (twice) and displays the offset correctly at 0, just as this other explorer was already doing before: https://ordinalswallet.com/inscription/8c4b0980f30b1a5faec0f252d38d3f68e4a97019655367d1c16b9867ddb66617i0

**Comment by rafaelcr** [comment]
This issue is now resolved! https://api.hiro.so/ordinals/v1/inscriptions/23198d6656ae23a9313eb3c2fffc8e6179e95905b92a042813feb705b6aeb1c5i0 returns the correct 0 offset.

(If you still see the old offset, though, you should clear your local browser cache)
