### ISSUE TITLE
Disable `x-frame-options: DENY` headers

### ISSUE THREAD

**Issue by janniks** [hirosystems/ordinals-api#56]
_Forgot to mention this on the call..._
Currently the API (content) responds with a `x-frame-options: DENY` header. Would it be possible to disable this? I didn't find explicit mention of this header in the codebase, so it may be default fastify logic (or similar)

This is needed for some iframe CSP (content security policy) changes on the frontend

**Comment by rafaelcr** [comment]
I believe this header is added by Cloudflare, @CharlieC3 do you know?

**Comment by CharlieC3** [comment]
@janniks @rafaelcr I add this header as a response for all of our deployed APIs; it's a good security standard to have. I've removed it for the Ordinals API, so you should be good now.
Do you know if we'll be able to add this back in the future?

**Comment by rafaelcr** [comment]
@CharlieC3 I think we could disable this header only for the `/ordinals/inscriptions/:id/content` endpoint, right @janniks ?

**Comment by janniks** [comment]
Sorry, I think we can revert the change again 🙈 Turns out there's more CSP issues in browsers that we can't fix currently.
But the originals ordinals.com behaves the same way _(e.g. [for redirects in ordinals content in iframes](https://ordinals.com/inscription/e0e10f332c1410151388c99b7b657be34839b4d01ff008f43e22623f55218f2di0))_  

If we do need this, /content will be enough -- but for now let's revert to whatever is a good security standard again 🙏

**Comment by CharlieC3** [comment]
@janniks haha reverted, thanks!

**Comment by CharlieC3** [comment]
@janniks Can you test the Ord-API in dev before I roll the change out further? In addition to removing the x-frame-options header, I also added the [frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) config to the CSP, allowing only parent sites matching `https://*.hiro.so` to embed iframes from that Ord-API endpoint. So this is more secure than just allowing anyone to embed the content.

**Comment by CharlieC3** [comment]
Hmm seems it does not. @rafaelcr Are you able to take a look at the dev Ord API deployment? Maybe it's not registered with the dev chainhooks deployment?
