### ISSUE TITLE
Owner address mismatch with ordinals.com

### ISSUE THREAD

**Issue by yknl** [hirosystems/ordinals-api#80]
Seems like there's a mismatch between the Hiro Ordinals indexer and ordinals.com. The same inscription below is listed as owned by different addresses.

https://ordinals.hiro.so/inscription/c83b62b5047e9a286add050a872e7a6eb365f107bfea7b66eec434bc3e326110i0

https://ordinals.com/inscription/c83b62b5047e9a286add050a872e7a6eb365f107bfea7b66eec434bc3e326110i0

**Comment by rafaelcr** [comment]
Thanks @yknl it looks like we're missing the last transfer event. I opened a new issue to take care of that https://github.com/hirosystems/ordinals-api/issues/81

**Comment by smcclellan** [comment]
This looks complete so I will close it. Please reopen this if more is needed.
