### ISSUE TITLE
Incorrect transfers returned for some inscription item

### ISSUE THREAD

**Issue by pake007** [hirosystems/ordinals-api#93]
sometimes the transfer API return incorrect results.

eg: transfers for inscription#199433
https://api.hiro.so/ordinals/v1/inscriptions/199433/transfers

after the txid 828b3323c3d5a7a7e4658cfb7f90d2a9d7bba2d73b111f6ee34a69e8ce602c64, the later txs are wrong
(compared with ordiscan)

and I think this will bring more mistakes in future because the new tx is generated from the previous tx, if I understand correctly

**Comment by rafaelcr** [comment]
This is a duplicate of #80

**Comment by pake007** [comment]
> This is a duplicate of #80

OK, thanks. Will you fix historical data?
