### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by utibeabasi6** [hirosystems/ordinals-api#98]
hey
i tried running the api again after the latest deploy and i get this error
`{"level":"error","time":"2023-06-15T11:19:20.595Z","pid":1,"hostname":"ordinals-api-writer-69f9cfd48f-5zp88","name":"ordinals-api","err":{"type":"ResponseStatusCodeError","message":"Response status code 404: Not Found","stack":"ResponseStatusCodeError: Response status code 404: Not Found\n    at getResolveErrorBodyCallback (/app/node_modules/undici/lib/api/api-request.js:172:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","name":"ResponseStatusCodeError","code":"UND_ERR_RESPONSE_STATUS_CODE","body":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <title>404 Not Found</title>\n</head>\n<body align=\"center\">\n    <div role=\"main\" align=\"center\">\n        <h1>404: Not Found</h1>\n        <p>The requested resource could not be found.</p>\n        <hr />\n    </div>\n    <div role=\"contentinfo\" align=\"center\">\n        <small>Rocket</small>\n    </div>\n</body>\n</html>","status":404,"statusCode":404,"headers":{"content-type":"text/html; charset=utf-8","server":"Rocket","permissions-policy":"interest-cohort=()","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","content-length":"383","date":"Thu, 15 Jun 2023 11:19:20 GMT"}},"msg":"EventServer unable to register predicate"}`

**Comment by rafaelcr** [comment]
Hi @utibeabasi6 this issue has been fixed in https://github.com/hirosystems/ordinals-api/releases/tag/v0.3.1
