### ISSUE TITLE
Cursed inscriptions not working?

### ISSUE THREAD

**Issue by yknl** [hirosystems/ordinals-api#99]
Are cursed inscriptions supposed to be returned from the API after this PR? https://github.com/hirosystems/ordinals-api/pull/85

The following cursed inscription is not showing up in the API response.
https://ordinals.com/inscription/42a6e9d1ac829407aee2933c0c6a413ab67c8b2b700854e15e0b86690267711ai0

API response for owner address does not contain the inscription:
https://api.hiro.so/ordinals/v1/inscriptions?address=bc1ptqlrrc8z0utza36sfe7sgynmwqs3r755fk7al2y6ld0kdrp6uw9qls627v

**Comment by rafaelcr** [comment]
The PR is merged into master and a release has been made, we're just working on getting a new index processed with cursed inscriptions included so we can deploy to production

**Comment by yknl** [comment]
Thanks @rafaelcr. Do you have any estimates on when the new index would be processed?

**Comment by smcclellan** [comment]
The indexing is complete & now we are ingesting -- we intend this to be resolved by tomorrow.
